spring:
  profiles:
    include: ${LED_MAIN_SERVER_PROFILES:admin-service, common, warehouse-service}
  application:
    name: ${LED_MAIN_SERVER_NAME:Warehouse Management System}
server:
  port: ${LED_MAIN_SERVER_PORT:8080}